// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BrowseFiltersController from "./browse_filters_controller"
application.register("browse-filters", BrowseFiltersController)

import Skos_collections_selector from "./skos_collections_selector"
application.register("skos-collections-selector", Skos_collections_selector)

import ClassSearchAutoCompleteController from "./class_search_auto_complete_controller"
application.register("class-search-auto-complete", ClassSearchAutoCompleteController)

import ContainerSplitterController from "./container_splitter_controller"
application.register("container-splitter", ContainerSplitterController)

import FairScoreHomeController from "./fair_score_home_controller"
application.register("fair-score-home", FairScoreHomeController)

import FairScoreLandscapeController from "./fair_score_landscape_controller"
application.register("fair-score-landscape", FairScoreLandscapeController)

import FairScoreSummaryController from "./fair_score_summary_controller"
application.register("fair-score-summary", FairScoreSummaryController)

import FormAutoCompleteController from "./form_auto_complete_controller"
application.register("form-auto-complete", FormAutoCompleteController)

import FormDisplayController from "./form_display_controller"
application.register("form-options-display", FormDisplayController)

import HistoryController from "./history_controller"
application.register("history", HistoryController)

import LanguageChangeController from "./language_change_controller"
application.register("language-change", LanguageChangeController)

import LoadChartController from "./load_chart_controller"
application.register("load-chart", LoadChartController)

import OntologyRelationsNetworkController from "./ontology_relations_network_controller"
application.register("ontology-relations-network", OntologyRelationsNetworkController)

import OntologyViewerTabsController from "./ontology_viewer_tabs_controller"
application.register("ontology-viewer-tabs", OntologyViewerTabsController)

import OntoportalAutocompleteController from "./ontoportal_autocomplete_controller"
application.register("ontoportal-autocomplete", OntoportalAutocompleteController)

import RecommenderController from "./recommender_controller"
application.register("recommender", RecommenderController)

import ShowFilterCountController from "./show_filter_count_controller"
application.register("show-filter-count", ShowFilterCountController)

import ShowModalController from "./show_modal_controller"
application.register("show-modal", ShowModalController)

import SimpleTreeController from "./simple_tree_controller"
application.register("simple-tree", SimpleTreeController)

import SkosCollectionColorsController from "./skos_collection_colors_controller"
application.register("skos-collection-colors", SkosCollectionColorsController)

import SparqlController from "./sparql_controller"
application.register("sparql", SparqlController)

import TextTruncateController from "./text_truncate_controller"
application.register("text-truncate", TextTruncateController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)

import TopnavResponsivenessController from "./topnav_responsiveness_controller"
application.register("topnav-responsiveness", TopnavResponsivenessController)

import TurboFrameController from "./turbo_frame_controller"
application.register("turbo-frame", TurboFrameController)

import TurboFrameErrorController from "./turbo_frame_error_controller"
application.register("turbo-frame-error", TurboFrameErrorController)

import SampleTextController from "./sample_text_controller"
application.register("sample-text", SampleTextController)

import AnnotatorController from "./annotator_controller"
application.register('annotator', AnnotatorController)

import FormUrlController from "./form_url_controller"
application.register('form-url', FormUrlController)

import OntologiesSelector from "./ontologies_selector_controller"
application.register("ontologies-selector", OntologiesSelector)

import ChartController from "./agents_statistics_chart"
application.register('agents-statistics', ChartController)

import MappingsController from "./mappings_visualization_controller"
application.register('mappings', MappingsController)

import ConceptsJsonButtonController from "./concepts_json_button_controller.js"
application.register('concepts-json', ConceptsJsonButtonController)

import ParentCategoriesSelectorController from "./parent_categories_selector_controller.js"
application.register('parent-categories-selector', ParentCategoriesSelectorController)

import AutoMappingFilterController from "./auto_mapping_filter_controller"
application.register('auto-mapping-filter', AutoMappingFilterController)